### ISSUE TITLE
Brew for M1/ARM?

### ISSUE THREAD

**Issue by jotaen** [jotaen/homebrew-klog#1]
No idea how to distinguish between the Intel and ARM binary for the download URL, so I’ve hard-coded to Intel for now.

**Comment by benjaminbauer** [comment]
I wrote this formula:
```ruby
class Klog < Formula
  desc "Time tracking CLI with plain-text files"
  homepage "https://klog.jotaen.net"
  url "https://github.com/jotaen/klog/archive/refs/tags/v3.2.tar.gz"
  sha256 "094c1450304470adfd53c3226e82b4ad429d9550e83765c32bfc941be9e91b8f"
  license "MIT"
  head "https://github.com/jotaen/klog.git"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args
  end
end

```

This will build klog locally and install the resulting binary. The catch: users who do NOT want to build it, rely on _bottles_. This does not seem to work for unofficial formulas, i.e. formulas outside of https://github.com/Homebrew/homebrew-core

Once the formula is accepted into homebrew-core, a build bot will build the bottles and inject a bottle block into the final formula. There will be bottles then for every supported architecture/OS combination. This should include arm64_* . See for example the formula for [ultralist](https://github.com/Homebrew/homebrew-core/blob/15b7f3da7d067ea1126d6552dbf7fb20a39a8abb/Formula/ultralist.rb)

So imo the way ahead is to do a PR for the above formula.

**Comment by jotaen** [comment]
Awesome, thanks for these starting points! I should set aside some time to look more into Brew (since I don’t use it myself), e.g. I didn’t know about the core repository.

(Note to self: [this is the docs on bottles](https://docs.brew.sh/Bottles), which basically expands on what @benjaminbauer already explained above.)
