### ISSUE TITLE
Automate homebrew release

### ISSUE THREAD

**Issue by jotaen** [jotaen/homebrew-klog#3]
It’s currently a manual process of me updating the version and the checksum here (which is tedious and prone to error).

**Comment by benjaminbauer** [comment]
This could be solved very nicely with [GH Actions](https://github.com/features/actions). A release on the klog repo can be used as the trigger for an action, that 

1. runs the generator script
2. commits the updated formula.rb
3. and merges it to main or create a PR

update:
I [created](https://github.com/benjaminbauer/homebrew-klog/tree/feature/build_via_gh_action) the workflow. It will do the above step 1 and 2. It runs on push. This covers the case where the generation of the formula changes.

I see two options going forward:

1. Extend the release workflow of klog to trigger this workflow to update the formula
2. Change the workflow here to run on release

Not sure which of the above is the better option wrt how GH actions are intended to be used. From a separation of concerns perspective I deem option 2 to be much cleaner. The main project does not need to be concerned with how different packaging systems handle a release.

**Comment by jotaen** [comment]
Thanks for looking into this!

I agree with you, I also like option 2 better for the sake of keeping things separated, even if that would require one manual step to kick off the release here. (Considering that there are only a handful of releases per year at most, that’s totally fine, though.)

An alternative option to `push` could be to just manually run the action via the Github UI. I’m using that mechanism in the [main klog repo already](https://github.com/jotaen/klog/blob/73250d96f4d95070e10410bb2d56c50d52d6f607/.github/workflows/release.yml#L1-L7) in order to prepare releases. That way, when you click on the “Actions” tab, you can kick off the job by clicking the “Run workflow” button:

<img width="400" alt="Screenshot 2023-01-22 at 12 04 11" src="https://user-images.githubusercontent.com/3618384/213912559-eefe8d67-5ba4-4f50-b365-4ddfbc92012b.png">

(In this case, the job is parametrised, but for the homebrew repo we wouldn’t need that.)

**Comment by benjaminbauer** [comment]
Good point, manual is sufficient for the frequency of releases. I will rebase those changes and open a PR

**Comment by jotaen** [comment]
Just tried the new automated action for the v6.0 release (https://github.com/jotaen/homebrew-klog/commit/d4c109a6242e142625cd4f94f1396bf02d520b49), and it worked like a charm! 🎉
