### ISSUE TITLE
⚠️⚠️⚠️ Looking for maintainer ⚠️⚠️⚠️

### ISSUE THREAD

**Issue by jotaen** [jotaen/homebrew-klog#8]
I’m not using Homebrew personally, so it probably doesn’t make sense for me to maintain this Homebrew package. (I actually didn’t even manage to set it up without the help of other people, the main work was done by @benjaminbauer.) So I’m looking for a volunteer who wants to take over this tap, and continue to maintain it.

In terms of maintenance, there really isn’t that much to do:

- [The Formula](https://github.com/jotaen/homebrew-klog/blob/main/Formula/klog.rb) seems to work well, and it is compatible with both ARM and Intel Macs.
- Releases are semi-automated, so in order to create a release, you only have to click one button to trigger a [Github action](https://github.com/jotaen/homebrew-klog/blob/main/.github/workflows/update_formula.yml). This automatically updates and commits the Formula file.
  - Nowadays, there are just a handful of klog releases per year – maybe around 5 or so.

The process of taking over this repo would be this:

1. The new maintainer forks this repository to their own Github account, from `jotaen/homebrew-klog` to e.g. `new-maintainers-github-handle/homebrew-klog`.
2. On the [klog project website](https://klog.jotaen.net/#get-klog), I link to the new tap repository.
   - That means that all new installations from then on would take place via `brew tap new-maintainers-github-handle/klog`.
   - Everyone with an existing installation has to migrate to the new tap.
3. I change the [deprecation notice](https://github.com/jotaen/homebrew-klog/blob/f4e098c20794d23872a6aef49154723a8d177a5b/Formula/klog.rb#L16) in this repo’s Formula, so that people with existing installations know where they can migrate to.
   - See [Homebrew docs](https://docs.brew.sh/Deprecating-Disabling-and-Removing-Formulae#deprecation) on the deprecation flag.
   - A potential alternative would be to use an on-the-fly migration via a [`tap_migrations.json` file](https://docs.brew.sh/Migrating-A-Formula-To-A-Tap), but I prefer for the ownership transferral to be transparent and explicit to end-users.
5. I eventually delete this repository at some point in the future, e.g. after 3 months or so.

**Comment by jotaen** [comment]
@benjaminbauer in case you’d be interested, we could make kurzer Prozess 😉

**Comment by benjaminbauer** [comment]
Hey @jotaen, thanks for your vote of confidence! I have not been using klog for some time. Recently I have been using https://github.com/zyedidia/eget for installing and updating single binary tools. I just tried installing klog with it with `eget jotaen/klog`, it did the right thing both on mac and linux.

So if you do not want to keep maintaining the homebrew formula, I vote to archive this repo and give a hint to eget for people who wish for a somewhat automated installation.

**Comment by jotaen** [comment]
Oh cool, eget looks very nice!

I’ll probably keep the repo for a bit, since it’s currently low-enough maintenance.

**Comment by Ovyerus** [comment]
I'm using Klog through Brew, and I'm interested in picking this repo up.

**Comment by jotaen** [comment]
Terrific, thanks for volunteering!

Could you fork (or otherwise take over) this repo and run the “Update Formula” action? This will automatically populate the latest download URL + hash to the formula file, committed under the `github-actions[bot]` user. (Of course, obviously, feel free to alter the release process as you like, but this is how it’s currently designed.)

You could let me know if it’s set up, so I can reference the `ovyerus/klog` tap on [the project website](https://klog.jotaen.net/#get-klog).

<img width="828" alt="Screenshot 2024-04-02 at 12 09 43" src="https://github.com/jotaen/homebrew-klog/assets/3618384/c3365c14-28dd-4a6f-a0b5-e971e92807df">

**Comment by Ovyerus** [comment]
Forked and ran the action. Tapped locally to double-check, and it has upgraded correctly 👍

**Comment by jotaen** [comment]
🎉 awesome, thank you! I’ve linked it [from the project page](https://klog.jotaen.net/#get-klog), and also referenced it [from this repo](https://github.com/jotaen/homebrew-klog/pull/11).

**Comment by Ovyerus** [comment]
Awesome!
